### PR TITLE
Fix | Fixed Searching Deeply Nested Elements

### PR DESCRIPTION
**Pull request by Sammyjo20**
There was a bug where when searching for deeply nested children that the reader wouldn't recognise the search. I found the bug was caused by the sequence matcher, so I have removed this.

@veewee I don't quite understand the _why_ here, maybe I can get away with just using matcher `nested` as all my tests pass still.

### CODE REVIEW

**Review by Sammyjo20 — COMMENTED** [review]
Self review

**Comment by veewee** [comment]
This is basically what I mentioned in [previous PR](https://github.com/saloonphp/xml-wrangler/pull/5): By using nested, you allow steps in between. 

So for example `items.item.0` can match on `tems.something.something.item.0` even though `something.something` was not added to the path.


`nested` is pretty much the same as `sequence`, but every matcher acts as a breakpoint for the next matcher - making it possible to leave gaps in between the search terms.

You could even drop the `document_element` matcher as and then the logic for detecting the root element can be removed as well. (Since it will either match or leave a gap in between)

To me it makes perfect sense to do it this way, but then you must accept that gaps between search-terms are allowed.

**Review by Sammyjo20 — COMMENTED** [review]
Self review

**Comment by Sammyjo20** [comment]
Fantastic! I think I've done it right? I've removed the extra logic that searches for the root now too! Thank you for your quick reply

**Comment by veewee** [comment]
Seems about what I had in mind previously yes! Seems to work, and is a lot less code. So nice!
Should have taken some time to explain it better maybe 🤔

**Comment by Sammyjo20** [comment]
It’s all good! I’m learning as I go along 😄 the marchers are still a little magical to me.

**Comment by veewee** [comment]
> It’s all good! I’m learning as I go along 😄 the marchers are still a little magical to me.

Yeah, I notice it's not very clear from the docs how it clicks.
I added this section to the docs today. It might be useful to read through it :)

https://github.com/veewee/xml/blob/main/docs/reader.md#how-does-it-work

**Comment by Sammyjo20** [comment]
Looks like a great example! I love you used the same breakfast menu example 😅

**Pull request merged**
